clusters:
  host:
    api: https://api.dummy-host.openshiftapps.com:6443
  members:
  - api: https://api.dummy-m1.openshiftapps.com:6443
    name: member-1
  - api: https://api.dummy-m2.openshiftapps.com:6443
    name: member-2
  - api: https://api.dummy-m3.openshiftapps.com:6443
    name: member-3

serviceAccounts:

- name: first-admin
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - install-operator
      - restart-deployment
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - disable-user
      - retarget-user
      - gdpr-delete
      - create-social-event
      - add-space-users
      clusterRoles:
      - edit
      - view
    - namespace: openshift-customer-monitoring
      roles:
      - install-operator
      - view-secrets
      - configure-monitoring
      clusterRoles:
      - edit
    - namespace: openshift-logging
      roles:
      - install-operator
      clusterRoles:
      - edit
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - install-operator
      - restart-deployment
      - view-secrets
      clusterRoles:
      - edit
      - view
    - namespace: openshift-customer-monitoring
      roles:
      - install-operator
      - view-secrets
      - configure-monitoring
      clusterRoles:
      - edit
    - namespace: openshift-logging
      roles:
      - install-operator
      clusterRoles:
      - edit
    - namespace: openshift-config-managed
      roles:
      - configure-monitoring
      clusterRoles:
      - edit
    clusterRoleBindings:
      clusterRoles:
      - manage-console-resources

- name: second-admin
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - disable-user
      - retarget-user
      - gdpr-delete
      - restart-deployment
      - create-social-event
      - add-space-users
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - restart-deployment
      - view-secrets
      clusterRoles:
      - view

- name: viewer
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

users:
- name: standard-user-admin
  id:
  - 123456
  - abc1234
  groups:
  - crtadmin-users-view
  - inspect-pods
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - edit-secrets
      clusterRoles:
      - view
    - namespace: openshift-customer-monitoring
      roles:
      - install-operator
      - view-secrets
      - configure-monitoring
      clusterRoles:
      - edit
    - namespace: openshift-logging
      clusterRoles:
      - view
    - namespace: sandbox-sre-host
      roles:
      - view-secrets
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - edit-secrets
      clusterRoles:
      - view
    - namespace: crw
      roles:
      - view-secrets
      clusterRoles:
      - view
    - namespace: openshift-customer-monitoring
      roles:
      - install-operator
      - view-secrets
      - configure-monitoring
      clusterRoles:
      - edit
    - namespace: openshift-logging
      clusterRoles:
      - view
    - namespace: sandbox-sre-member
      roles:
      - view-secrets
      clusterRoles:
      - view

- name: standard-user-viewer
  id:
  - 987654
  groups:
  - crtadmin-users-view
  - kubesaw-team
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: other-component-admin
  id:
  - 561234287
  - f:528d:some-admin
  member:
    roleBindings:
    - namespace: some-component
      roles:
      - approve-operator-update
      clusterRoles:
      - edit
    clusterRoleBindings:
      clusterRoles:
      - list-operators-group

- name: other-component-viewer
  id:
  - 5412345
  member:
    roleBindings:
    - namespace: first-component
      clusterRoles:
      - view
    - namespace: second-component
      clusterRoles:
      - view
